import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs'
import Shimmer from "@/shimmer/shimmer";
import { ThemeProvider } from "@/components/theme-provider"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} mt-25`}>

          <ClerkLoading>
            <Shimmer />
          </ClerkLoading>

          <ClerkLoaded>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange >

              <div className="fixed inset-0 -z-10 w-full h-full bg-[radial-gradient(#dadde2_1px,transparent_1px)] bg-repeat bg-size-[16px_16px] dark:bg-[radial-gradient(#393e4a_1px,transparent_1px)] dark:bg-repeat dark:bg-size- dark:bg-top-left" />
              {children}

            </ThemeProvider>
          </ClerkLoaded>


        </body>
      </html>
    </ClerkProvider>
  );
}
